apps/funcionarios/urls.py
from django.urls import path
from .views import (
    FuncionariosList,
    FuncionarioEdit,
    FuncionarioDelete,
    FuncionarioNovo,
    Pdf
)

from .views import relatorio_funcionarios

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('editar/<int:pk>', FuncionarioEdit.as_view(), name='update_funcionario'),
    path('deletar/<int:pk>', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('novo/', FuncionarioNovo.as_view(), name='create_funcionario'),
    path('relatorio_funcionarios/', relatorio_funcionarios, name='relatorio_funcionarios'),
    path('relatorio_funcionarios_html/', Pdf.as_view(), name='relatorio_funcionarios_html'),
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

# importar o viewset programado
from apps.funcionarios.api.views import FuncionarioViewSet
from apps.registro_hora_extra.api.views import RegistroHoraExtraViewSet

# imports do rest framework
from rest_framework import routers
from apps.core import views

# import url translate
from django.conf.urls.i18n import i18n_patterns

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/banco-horas', RegistroHoraExtraViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresa/', include('apps.empresas.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
static(settings, etc) é uma gambiarra para em ambiente de desenvolvimento ver o arquivo upado
'''

apps/documentos/models.py
from django.db import models
from apps.funcionarios.models import Funcionario


# Create your models here.
class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(
    Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')  # quando fizer upload do arquivo vai para pasta documentos

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])
    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg, Count, Min, Sum
from apps.departamentos.models import Departamentos   # um usuario pode estar em multiplos departamentos
from apps.empresas.models import Empresa
from django.urls import reverse

# Create your models here.
class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)    # Protect nao apaga em cascata
    departamentos = models.ManyToManyField(Departamentos)   # foreingkey de um para n
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)
    imagem = models.ImageField()
    de_ferias = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    # cria um campo na classe funcionario que recebe soma das horas carregadas no queryset regitrohoraextra_set
    @property
    def total_horas_extra(self):
        total = self.registrohoraextra_set.filter(utilizada=False).aggregate(Sum('horas'))['horas__sum']
        # se total for none o python retorna 0
        return total or 0

    def __str__(self):
        return self.nome

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse
from apps.funcionarios.models import Funcionario

# Create your models here.
class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.funcionario.id])

    def __str__(self):
        return self.motivo

apps/funcionarios/api/views.py
from rest_framework import viewsets
from apps.funcionarios.api.serializers import FuncionarioSerializer
from apps.funcionarios.models import Funcionario
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication

class FuncionarioViewSet(viewsets.ModelViewSet):
    queryset = Funcionario.objects.all()
    serializer_class = FuncionarioSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

apps/funcionarios/views.py
import io

from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from django.contrib.auth.models import User
from reportlab.pdfgen import canvas

from .models import Funcionario

# para geracao de relatorio pdf a partir de html

from django.template.loader import get_template
import xhtml2pdf.pisa as pisa

# para translate
from django.utils.translation import gettext as _

# Create your views here.


class FuncionariosList(ListView):
    model = Funcionario

    '''
        reescreve ou subscreve uma funcao ja existente do django onde devera retornar somente os 
        funconarios referentes a empresa logada
    '''
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['report_button'] = _("Employee report")
        return context


    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada) #envia para o queryset o filtro desejado


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    # redefino o methodo do django
    def form_valid(self, form):
        funcionario =  form.save(commit=False) #somente cria o objeto em memoria e nao no banco
        #username do usuario sugerido
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]

        #defino a empresa do funcionario
        funcionario.empresa = self.request.user.funcionario.empresa
        #crio um usuario para este funcionario
        funcionario.user = User.objects.create(username= username)
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)


def relatorio_funcionarios(request):
    response = HttpResponse(content_type='application/pdf')

    # para baixar o relatorio (download) quando clicado no link
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'

    # obrigatorio criar o buffer e objeto canvas
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)

    # escrevendo no relatorio coordenadas y e x... tipo @say
    p.drawString(200, 810, 'Relatório de Funcionários')

    # fazendo uma query para buscar o cadastro de funcionarios (all)
    # funcionarios = Funcionario.objects.all()

    # filtrando uma query por empresa. Passa o where para a query
    funcionarios = Funcionario.objects.filter(empresa=request.user.funcionario.empresa)

    str_ = 'Nome: %s | Hora Extra: %.2f'

    # construindo linha abaixo do titulo
    p.drawString(0, 800, '_' * 150)

    y = 750
    for funcionario in funcionarios:
        p.drawString(10, y, str_ % (funcionario.nome, funcionario.total_horas_extra))
        y -= 20

    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response

class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode("UTF-8")), response)

        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type='application/pdf')
            response['Content-Disposition'] = 'attachment;filename=%s.pdf' % filename
            return response
        else:
            return HttpResponse("Error Rendering PDF", status=400)


class Pdf(View):

    def get(self, request):
        params = {
            'today': 'Variavel today',
            'sales': 'Variavel Sales',
            'request': request,
        }
        return Render.render('funcionarios/relatorio.html', params, 'myfile')

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
    Edit
    <form method="POST">
        {% csrf_token %}
        <h1>Você tem certeza que quer apagar {{ obj }}</h1>
        {{ form }}

        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
    <form method="POST">
        {% csrf_token %}

        {{ form|bootstrap }}

        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
    <br>
    <h2>Documentos</h2>
    <ul>
        <!-- for para apresentar os documentos do usuario -->
        {% for documento in object.documento_set.all %}
           <li>
                <a href="{{ documento.arquivo.url }}">{{ documento.descricao }}</a> <br>
           </li>
        {% endfor %}
    </ul>

    {% if object %}
        <a href="{% url 'create_documento' object.id %}" class="btn btn-success">
            Adicionar documento
        </a>
    {% endif %}

    <br>

    <!--banco de horas-->
    <h2>Banco de Horas</h2>
    <ul>
        <!-- for para apresentar os documentos do usuario -->
        {% for registro_hora in object.registrohoraextra_set.all %}
            <li>
                <a href="{% url 'update_hora_extra' registro_hora.id %}">
                    {{ registro_hora.motivo }} | {{ registro_hora.horas }} <br>
                </a>
                <br>
            </li>
        {% endfor %}
    </ul>

    <h3>Total de Horas Extras: {{ object.total_horas_extra }}</h3>
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
    <br>

    <div class="container">
        <h3>Lista de Funcionários</h3>
        <div class="row">
            <div class="col-sm-6">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Funcionário</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for funcionario in object_list %}
                            <tr>
                                <th scope="row">{{ funcionario.id }}</th>
                                <td>{{ funcionario.nome }}</td>
                                <td><a href="{% url 'update_funcionario' funcionario.id %}"
                                       class="btn btn-primary"</a>Alterar</td>
                                <td><a href="{% url 'delete_funcionario' funcionario.id %}"
                                       class="btn btn-danger">Deletar</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>

        <a href="{% url 'create_funcionario' %}" class="btn btn-info">Novo</a>
        <a href="{% url 'relatorio_funcionarios' %}" class="btn btn-warning">
            {{ report_button }}
        </a>

        <!-- relatorio em pdf a partir de html-->
        <a href="{% url 'relatorio_funcionarios_html' %}" class="btn btn-warning">
            Relatorio de Funcionarios HTML
        </a>
    </div>
<br>

{% endblock %}

apps/funcionarios/templates/funcionarios/relatorio.html
{% extends 'base.html' %}

{% block staticcss %}
    <style>
        .teste { color: red; }
    </style>
{% endblock %}

{% block main %}
    <h1 class="teste">Meu Relatório</h1>
    <h2>{{ sales }}</h2>

{% endblock %}